name: Release

on:
  push:
    tags:
      - "*"

env:
  RELEASE_ENV: true
  WIGWAM_STATIC_CDN: ${{ secrets.WIGWAM_STATIC_CDN }}
  WIGWAM_INDEXER_API: ${{ secrets.WIGWAM_INDEXER_API }}
  WIGWAM_INDEXER_API_KEY: ${{ secrets.WIGWAM_INDEXER_API_KEY }}
  WIGWAM_INFURA_API_KEY: ${{ secrets.WIGWAM_INFURA_API_KEY }}
  WIGWAM_ANALYTICS_API_KEY: ${{ secrets.WIGWAM_ANALYTICS_API_KEY }}
  WIGWAM_OPEN_LOGIN_CLIENT_ID: ${{ secrets.WIGWAM_OPEN_LOGIN_CLIENT_ID }}
  WIGWAM_ON_RAMP_API_KEY: ${{ secrets.WIGWAM_ON_RAMP_API_KEY }}
  WIGWAM_ON_RAMP_API_URL: ${{ secrets.WIGWAM_ON_RAMP_API_URL }}

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Check TypeScript
        run: yarn ts

      - name: Check ESLint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Create app build
        run: yarn build:chrome & yarn build:firefox

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            dist/prod/chrome.zip
            dist/prod/firefox.xpi
